# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
    name: statping.ng
spec:
    description: Web and App Status Monitoring for Any Type of Project
    coverImage: https://statping-ng.github.io/assets/img/banner.png
    icon: https://statping-ng.github.io/assets/img/banner.png
    tags:
        - Monitoring
    readme: |-
        # Statping-ng - Status Page & Monitoring Server
        An easy to use Status Page for your websites and applications. Statping will automatically fetch the application and render a beautiful status page with tons of features for you to build an even better status page. This Status Page generator allows you to use MySQL, Postgres, or SQLite on multiple operating systems.        
        
        [Website](https://statping-ng.github.io)|[Wiki](https://github.com/statping-ng/statping-ng/wiki)

    services:
        - name: statping.ng
          icon: https://statping-ng.github.io/assets/img/banner.png
          template: PREBUILT
          spec:
            source:
                image: adamboutcher/statping-ng:latest
            ports:
                - id: web
                  port: 8080
                  type: HTTP
            volumes:
                - id: statping-data
                  dir: /app
localization:
    zh-CN:
        description: Statping-ng - 状态页 & 监控服务
        readme: |
            一个易于使用的网站和应用程序状态页面。Statping 将自动获取应用程序并呈现一个漂亮的状态页面，具有许多功能，可以帮助您构建更好的状态页面。这个状态页面生成器允许您在多个操作系统上使用 MySQL、Postgres 或 SQLite。